[config]
# ...

[templates.hyprland]
input_path = 'path/to/templates'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.kitty]
input_path = 'path/to/template'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'
